### ISSUE TITLE
Rapns.push hangs on receiving feedback

### ISSUE THREAD

**Issue by krzyzak** [ileitch/rapns#117]
Hi there.
I’m trying to switch from apn_on_rails to rapns.
Everything went pretty smooth until I started working on devlivering notifications.
Since we don’t have that much notifications, we’re using resque + resque scheduler, which runs our notifications worker every 10 seconds. Its code is trivial, it simply runs `Rapns.push`.
However, I noticed, that this worker doesn’t quit.
I tried manually run this on console, and it hangs only on first call:

```
rb(main):026:0> Rapns.push
   (1.2ms)  SELECT COUNT(*) FROM "rapns_apps"
  Rapns::App Load (1.0ms)  SELECT "rapns_apps".* FROM "rapns_apps"
  Rapns::Notification Load (8.7ms)  SELECT "rapns_notifications".* FROM "rapns_notifications" WHERE "rapns_notifications"."app_id" IN (1) AND (delivered = 'f' AND failed = 'f' AND (deliver_after IS NULL OR deliver_after < '2013-03-20 08:36:17.565673'))
   (0.7ms)  BEGIN
   (1.9ms)  UPDATE "rapns_notifications" SET "delivered" = 't', "delivered_at" = '2013-03-20 08:36:17.844487', "updated_at" = '2013-03-20 08:36:17.846559', "registration_ids" = '---
...
' WHERE "rapns_notifications"."type" IN ('Rapns::Apns::Notification') AND "rapns_notifications"."id" = 1
   (2.7ms)  COMMIT
^CIRB::Abort: abort then interrupt!!
    from /app/vendor/bundle/ruby/1.9.1/gems/rapns-3.1.0/lib/rapns/daemon/apns/feedback_receiver.rb:33:in `call'
    from /app/vendor/bundle/ruby/1.9.1/gems/rapns-3.1.0/lib/rapns/daemon/apns/feedback_receiver.rb:33:in `join'
    from /app/vendor/bundle/ruby/1.9.1/gems/rapns-3.1.0/lib/rapns/daemon/apns/feedback_receiver.rb:33:in `stop'
    from /app/vendor/bundle/ruby/1.9.1/gems/rapns-3.1.0/lib/rapns/daemon/apns/app_runner.rb:26:in `stopped'
    from /app/vendor/bundle/ruby/1.9.1/gems/rapns-3.1.0/lib/rapns/daemon/app_runner.rb:77:in `stop'
    from /app/vendor/bundle/ruby/1.9.1/gems/rapns-3.1.0/lib/rapns/daemon/app_runner.rb:46:in `map'
    from /app/vendor/bundle/ruby/1.9.1/gems/rapns-3.1.0/lib/rapns/daemon/app_runner.rb:46:in `stop'
    from /app/vendor/bundle/ruby/1.9.1/gems/rapns-3.1.0/lib/rapns/daemon.rb:58:in `shutdown'
    from /app/vendor/bundle/ruby/1.9.1/gems/rapns-3.1.0/lib/rapns/push.rb:10:in `push'
    from (irb):26
    from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/commands/console.rb:47:in `start'
    from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/commands/console.rb:8:in `start'
    from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

When I abort it, and I try to `Rapns.push` again, it works as expected. I tried to debug this by myself, and it seems that it waits for joining threads, however further debugging was too hard for me.

NB: I’m receiving notifications correctly.

I’m running on heroku, cedar, ruby 1.9.3, rails 3.2.12.

**Comment by krzyzak** [comment]
Ok. now it’s even more strange.
I switched to edge rapns version, and under console:

```> @time = Time.now; Rapns.push; puts "Execution time: #{Time.now - @time}"
   (1.3ms)  SELECT COUNT(_) FROM "rapns_apps"
  Rapns::App Load (1.7ms)  SELECT "rapns_apps"._ FROM "rapns_apps"
  Rapns::Notification Load (21.8ms)  SELECT "rapns_notifications".\* FROM "rapns_notifications" WHERE "rapns_notifications"."app_id" IN (1) AND (delivered = 'f' AND failed = 'f' AND (deliver_after IS NULL OR deliver_after < '2013-03-20 11:45:35.195261'))
Execution time: 60.718008942

``````
I suppose that it has some connection with ```config.feedback_poll = 60```.
However my worker works for 10 minutes right now, so I suppose it again hangs…
``````

**Comment by ileitch** [comment]
Yep, this is a known issue. I'll try fix and push a new release on the weekend.

**Comment by krzyzak** [comment]
> Yep, this is a known issue. 

hmm, couldn’t find corresponding issue, sorry.

>  I'll try fix and push a new release on the weekend.

It would be great, thanks in advance!
