### ISSUE TITLE
(Unable to use Rapns in staging env) ArgumentError: comparison of Fixnum with Array failed 

### ISSUE THREAD

**Issue by ringular** [ileitch/rapns#131]
Hey @ileitch. Thank you so much for this Gem.

I'm having issues with getting Rapns working in a staging environment. 
Everything works well when running in development on my localhost, but when in Staging (using AWS) I am unable to start the Daemon or call `Rapns.push`

When calling `bundle exec rapns staging` I get no error, but the notifications are not delivered.

When using  `bundle exec rapns staging -f` or when trying to call `Rapns.push` from the rails console, I get:

```
[2013-05-29 06:54:20] [ios] Started, 1 handler.
[2013-05-29 06:54:20] [ERROR] [ios] Exception raised during startup. Notifications will not be delivered for this app.
/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/logger.rb:365:in `<': comparison of Fixnum with Array failed (ArgumentError)
    from /usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/logger.rb:365:in `add'
    from .../shared/bundle/ruby/1.9.1/gems/activesupport-3.2.7/lib/active_support/buffered_logger.rb:80:in `add'
    from .../shared/bundle/ruby/1.9.1/gems/activesupport-3.2.7/lib/active_support/buffered_logger.rb:90:in `error'
    from .../shared/bundle/ruby/1.9.1/gems/rapns-3.3.0/lib/rapns/logger.rb:53:in `log'
    from .../shared/bundle/ruby/1.9.1/gems/rapns-3.3.0/lib/rapns/logger.rb:28:in `error'
    from .../shared/bundle/ruby/1.9.1/gems/rapns-3.3.0/lib/rapns/daemon/app_runner.rb:34:in `rescue in sync_app'
    from .../shared/bundle/ruby/1.9.1/gems/rapns-3.3.0/lib/rapns/daemon/app_runner.rb:30:in `sync_app'
    from .../shared/bundle/ruby/1.9.1/gems/rapns-3.3.0/lib/rapns/daemon/app_runner.rb:20:in `block in sync'
    from .../shared/bundle/ruby/1.9.1/gems/rapns-3.3.0/lib/rapns/daemon/app_runner.rb:20:in `each'
    from .../shared/bundle/ruby/1.9.1/gems/rapns-3.3.0/lib/rapns/daemon/app_runner.rb:20:in `sync'
    from .../shared/bundle/ruby/1.9.1/gems/rapns-3.3.0/lib/rapns/daemon.rb:47:in `start'
    from .../shared/bundle/ruby/1.9.1/gems/rapns-3.3.0/bin/rapns:36:in `<top (required)>'
    from .../shared/bundle/ruby/1.9.1/bin/rapns:23:in `load'
    from .../shared/bundle/ruby/1.9.1/bin/rapns:23:in `<main>'
```

Again, everything works well on my local machine. Any ideas? Thanks so much in advance!

**Comment by ileitch** [comment]
Is your logger configured differently in staging compared to development?
