### ISSUE TITLE
no such column error

### ISSUE THREAD

**Issue by reejosamuel** [ileitch/rapns#163]
This error is being thrown when `rapns development -f`

``` ruby
[2013-09-14 22:01:20] [WARNING] Lost connection to database, reconnecting...
[2013-09-14 22:01:20] [WARNING] Attempt 1
[2013-09-14 22:01:20] [WARNING] Database reconnected
[2013-09-14 22:01:20] [ERROR] ActiveRecord::StatementInvalid, SQLite3::SQLException: no such column: true: UPDATE "rapns_notifications" SET delivered = true, delivered_at = '2013-09-14 18:01:20.334655' WHERE "rapns_notifications"."id" IN (1)
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/sqlite3-1.3.8/lib/sqlite3/database.rb:91:in `initialize'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/sqlite3-1.3.8/lib/sqlite3/database.rb:91:in `new'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/sqlite3-1.3.8/lib/sqlite3/database.rb:91:in `prepare'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/activerecord-3.2.9/lib/active_record/connection_adapters/sqlite_adapter.rb:246:in `block in exec_query'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/activerecord-3.2.9/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/activesupport-3.2.9/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/activerecord-3.2.9/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/activerecord-3.2.9/lib/active_record/connection_adapters/sqlite_adapter.rb:242:in `exec_query'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/activerecord-3.2.9/lib/active_record/connection_adapters/sqlite_adapter.rb:268:in `exec_delete'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/activerecord-3.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:96:in `update'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/activerecord-3.2.9/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `update'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/activerecord-3.2.9/lib/active_record/relation.rb:294:in `update_all'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/rapns-3.4.1/lib/rapns/daemon/store/active_record.rb:46:in `block in mark_batch_delivered'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/rapns-3.4.1/lib/rapns/daemon/store/active_record/reconnectable.rb:18:in `block in with_database_reconnect_and_retry'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/activerecord-3.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/rapns-3.4.1/lib/rapns/daemon/store/active_record/reconnectable.rb:17:in `with_database_reconnect_and_retry'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/rapns-3.4.1/lib/rapns/daemon/store/active_record.rb:45:in `mark_batch_delivered'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/rapns-3.4.1/lib/rapns/daemon/batch.rb:81:in `complete_delivered'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/rapns-3.4.1/lib/rapns/daemon/batch.rb:69:in `block in complete'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/rapns-3.4.1/lib/rapns/daemon/batch.rb:67:in `each'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/rapns-3.4.1/lib/rapns/daemon/batch.rb:67:in `complete'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/rapns-3.4.1/lib/rapns/daemon/batch.rb:52:in `block in notification_processed'
<internal:prelude>:10:in `synchronize'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/rapns-3.4.1/lib/rapns/daemon/batch.rb:50:in `notification_processed'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/rapns-3.4.1/lib/rapns/daemon/delivery_handler.rb:47:in `handle_next_notification'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/rapns-3.4.1/lib/rapns/daemon/delivery_handler.rb:13:in `block (2 levels) in start'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/rapns-3.4.1/lib/rapns/daemon/delivery_handler.rb:12:in `loop'
/Users/reejosamuel/.rvm/gems/ruby-1.9.3-p448/gems/rapns-3.4.1/lib/rapns/daemon/delivery_handler.rb:12:in `block in start'
[2013-09-14 22:01:20] [WARNING] Lost connection to database, reconnecting...
[2013-09-14 22:01:20] [WARNING] Attempt 1
[2013-09-14 22:01:20] [WARNING] Database reconnected
```

**Comment by reejosamuel** [comment]
you can close this. I just googled another solution from https://github.com/ileitch/rapns/issues/160
