### ISSUE TITLE
Rails migration issue during initialization

### ISSUE THREAD

**Issue by vnu** [ileitch/rapns#172]
Hi, I am trying to migrate after running `rails g rapns` on rails 3.2, ruby 1.9.3

And when I do `rake db:migrate`, its aborted

``` ruby
PG::Error: ERROR:  relation "apps" does not exist
: ALTER TABLE "rapns_notifications" ADD FOREIGN KEY ("app_id") REFERENCES "apps" ("id")/....

.
.
.
/Users/vnu/.rvm/gems/ruby-1.9.3-p392@vnu/gems/activerecord-3.2.14/lib/active_record/migration.rb:458:in `method_missing'
/Users/vnu/.rvm/gems/ruby-1.9.3-p392@vnu/gems/activerecord-3.2.14/lib/active_record/migration.rb:334:in `method_missing'
/Users/vnu/cp/vnu/db/migrate/20131003200350_add_gcm.rb:40:in `up'
/Users/vnu/.rvm/gems/ruby-1.9.3-p392@vnu/gems/activerecord-3.2.14/lib/active_record/migration.rb:370:in `up'
```

@ileitch Looks like some references to proper models are missing. Any help is appreciated. Thanks.

**Comment by vnu** [comment]
Nm , Issue from my end
