### ISSUE TITLE
Certificate has been revoked (Rails Console & Controller both)

### ISSUE THREAD

**Issue by atebit** [ileitch/rapns#205]
In the background process, this fails and I see the log tail, but I never get the notification to the phone. _(same error as below)_

I just ran the following in Heroku rails console and I get the same error log, except the notification makes it's way to the phone! _(confusing)_

```
app = Rpush::Apns::App.new
app.name = "teamhop_ios"
app.certificate = ENV['IOS_NOTIFICATION_CERT_PATH']
app.environment = "production"
app.password = ENV['IOS_NOTIFICATION_CERT_PATH']
app.connections = 1
app.save!

n = Rpush::Apns::Notification.new
n.app = Rpush::Apns::App.find_by_name("teamhop_ios")
n.device_token = user.device_token #valid
n.alert = "test from server"
n.data = { foo: :bartest }
n.save!
```

In the controller I run `Rpush.delay.push` (which works) and in the console I ran `Rpush.push` (which worked)

Now, here's the error log from console (same as worker):
```
[2017-03-29 20:13:35] [ERROR] [teamhop_ios] Certificate has been revoked.
SSL_connect returned=1 errno=0 state=SSLv3 read finished A: sslv3 alert certificate revoked
[2017-03-29 20:13:35] [WARNING] [teamhop_ios] Will retry 6 notifications after 2017-03-29 20:13:45 due to error (Rpush::Daemon::TcpConnectionError, OpenSSL::SSL::SSLError, SSL_connect returned=1 errno=0 state=SSLv3 read finished A: sslv3 alert certificate revoked)
[2017-03-29 20:13:35] [ERROR] Rpush::Daemon::TcpConnectionError, OpenSSL::SSL::SSLError, SSL_connect returned=1 errno=0 state=SSLv3 read finished A: sslv3 alert certificate revoked
/app/vendor/bundle/ruby/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/tcp_connection.rb:162:in `rescue in connect_socket'
/app/vendor/bundle/ruby/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/tcp_connection.rb:134:in `connect_socket'
/app/vendor/bundle/ruby/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/tcp_connection.rb:40:in `connect'
/app/vendor/bundle/ruby/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/tcp_connection.rb:69:in `write'
/app/vendor/bundle/ruby/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/apns/delivery.rb:12:in `perform'
/app/vendor/bundle/ruby/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/dispatcher/apns_tcp.rb:32:in `block in dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/dispatcher/apns_tcp.rb:31:in `synchronize'
/app/vendor/bundle/ruby/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/dispatcher/apns_tcp.rb:31:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/dispatcher_loop.rb:66:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/dispatcher_loop.rb:35:in `block (2 levels) in start'
/app/vendor/bundle/ruby/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/dispatcher_loop.rb:25:in `loop'
/app/vendor/bundle/ruby/2.3.0/gems/rpush-2.7.0/lib/rpush/daemon/dispatcher_loop.rb:25:in `block in start'
=> {}
```

Also, this is the error that I get on Airbrake:
`Modis::RecordInvalid: Certificate value must contain a certificate and a private key.`

If it helps:
```
ruby '2.3.1'
gem 'rails', '5.0.0.1'
gem 'sidekiq'
gem 'redis'
gem 'rpush-redis'
gem 'rpush'
```

Any help would be awesome. Need to get this stuff done soon... :/

**Comment by atebit** [comment]
Didn't realize that this was the old repo, oops, moving here and closing: https://github.com/rpush/rpush/issues/348
